sudo: required

language: python

services:
  - docker

install:
  - docker build -t deployer .

script:
  - docker run -ti --rm -e DP_ECS_CLUSTER=example-cluster -e DP_ECR_REGISTRY=0123456789 deployer inv precommit